import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ClerkProvider ,
  
  SignedIn,
  SignIn,
  SignedOut} from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SignedOut>
         <div className="flex flex-col items-center justify-center min-h-screen min-w-screen bg-slate-200">
           <SignIn  routing="hash"/>
         </div>
        </SignedOut>
        <SignedIn>
        {children}
        </SignedIn>
      </body>
    </html>
    </ClerkProvider>
  );
}
